In [1]:
import numpy as np

In [2]:
mylist = [1,2,3]
type(mylist)

list

In [3]:
np.array(mylist)

array([1, 2, 3])

In [4]:
my_arr = np.array(mylist)
my_arr

array([1, 2, 3])

In [5]:
type(my_arr)

numpy.ndarray

In [6]:
my_matrix = [[1,2,3], [4,5,6],[7,8,9]]
my_matrix

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [7]:
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [9]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

In [10]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [11]:
np.zeros((2,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones((3,6))

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [13]:
type(np.ones((3,6)))

numpy.ndarray

## linspace

In [14]:
np.linspace(0,10,15) # going from 0 to 10 it gives 15 number

array([ 0.        ,  0.71428571,  1.42857143,  2.14285714,  2.85714286,
        3.57142857,  4.28571429,  5.        ,  5.71428571,  6.42857143,
        7.14285714,  7.85714286,  8.57142857,  9.28571429, 10.        ])

In [15]:
len(np.linspace(0,10,15))

15

In [16]:
#Identity Matrix
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

# Random

### Rand

In [17]:
np.random.rand(1) # rand gives number from 0(exclude) to 1(include)

array([0.43022751])

In [34]:
np.random.rand(5,2)

array([[0.27134903, 0.82873751],
       [0.35675333, 0.28093451],
       [0.54269608, 0.14092422],
       [0.80219698, 0.07455064],
       [0.98688694, 0.77224477]])

### Randn - to create samples from a standard normal distribution

In [19]:
np.random.randn(9)

array([ 0.14213831, -0.71685124,  1.79671125,  0.53187062, -0.10568974,
        0.73311288,  0.49227962, -0.49858113, -0.66039009])

In [20]:
np.random.randn(5,2)

array([[-1.28672548, -0.11543138],
       [-1.02159471,  0.55013401],
       [-0.17553662, -0.82199555],
       [-0.91406015, -1.4785127 ],
       [-0.2736961 ,  1.03102682]])

### Randint

In [21]:
np.random.randint(0,101,9)

array([ 0, 61, 10, 27,  5, 48, 16, 17, 60])

In [22]:
np.random.randint(0,101,(3,3))

array([[45, 79, 38],
       [45, 76, 69],
       [32, 58, 79]])

In [23]:
np.random.seed(42)
np.random.rand(4)

array([0.37454012, 0.95071431, 0.73199394, 0.59865848])

In [24]:
arr = np.arange(0,25)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ranarr = np.random.randint(0,101,10)
ranarr

array([82, 86, 74, 74, 87, 99, 23,  2, 21, 52])

In [27]:
ranarr.max()

99

In [28]:
ranarr.min()

2

In [29]:
ranarr.argmax() # index value of maximum number

5

In [30]:
ranarr.argmin() # index value if minimum number

7

In [31]:
ranarr.dtype

dtype('int32')

In [32]:
ranarr.shape

(10,)