In [1]:
import numpy as np

In [2]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [3]:
arr[2]

2

In [4]:
arr[1:5]

array([1, 2, 3, 4])

In [5]:
arr[:5]

array([0, 1, 2, 3, 4])

In [6]:
arr[1:4:2]

array([1, 3])

## Broadcasting - setting a spcefic value in the array

In [7]:
arr[0:5] = 100

In [8]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [9]:
arr = np.arange(0,11)

In [10]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## Slicing

In [11]:
slice_of_arr = arr[0:5]
slice_of_arr

array([0, 1, 2, 3, 4])

In [12]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99])

In [13]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

In [14]:
arr_copy = arr.copy()

In [15]:
arr_copy[:] = 100

In [16]:
arr_copy

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [17]:
arr

array([99, 99, 99, 99, 99,  5,  6,  7,  8,  9, 10])

# 2-dim

In [18]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [19]:
arr_2d.shape

(3, 3)

In [20]:
arr_2d[0]

array([ 5, 10, 15])

In [21]:
arr_2d[0][1]

10

In [22]:
arr_2d[0,1]

10

In [23]:
arr_2d[:2,1:] # 2 is columns and 1 is rows

array([[10, 15],
       [25, 30]])

In [24]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [25]:
arr > 5

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [26]:
bool_arr = arr > 5
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [27]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [28]:
arr[arr > 5]

array([ 6,  7,  8,  9, 10])

In [29]:
len(arr[arr > 5])

5

In [30]:
a = np.array([x for x in range(27)])
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [31]:
np.arange(0,27)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26])

In [32]:
x = np.array([1,2,3,4])
np.all(x) # checks for 0 in the array

True

In [33]:
np.any(x) # checks for any non-zero in the array

True

In [34]:
x.shape, x.itemsize

((4,), 4)

In [35]:
np.ones(10)*5

array([5., 5., 5., 5., 5., 5., 5., 5., 5., 5.])

In [36]:
arr1 = np.arange(7,10)
arr1

array([7, 8, 9])